---
- hosts: webserver
  gather_facts: true
  remote_user: vagrant
  become: yes

  tasks:
    - name: install packages required for webserver
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

    - name: ensure apache2 is started
      service: name=apache2 state=started enabled=yes

    - name: ensure mod_wsgi enabled
      apache2_module: state=present name=wsgi
      notify: restart apache2
  
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted