---
- hosts: loadbalancer
  gather_facts: true
  remote_user: vagrant
  become: yes

  tasks:

    - name: install required tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - python-httplib2

    - name: install nginx
      apt: name=nginx state=present update_cache=yes

    - name: ensure nginx is started
      service: name=nginx state=started enabled=yes

    - name: configure load balancing
      template: src=../templates/nginx.conf.j2 dest=/etc/nginx/sites-available/demo mode=0644
      notify: restart nginx

    - name: deactivate default nginx site
      file: path=/etc/nginx/{{item}} state=absent
      with_items:
        - sites-available/default
        - sites-enabled/default
      notify: restart nginx

    - name: activate demo load balancing
      file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted