# -*- mode: ruby -*-
# vi: set ft=ruby :

# First module's Vagrantfile. For basics of Ansible, this is enough...

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true

  config.vm.define "inst01" do |inst01|
    inst01.vm.box = "ubuntu/trusty64"
    inst01.vm.hostname = "inst01"
    inst01.vm.network :private_network, ip: "10.10.12.63"
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    config.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
    config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
    config.vm.provision 'shell', inline: "echo \"#{ssh_pub_key}\" >> /home/vagrant/.ssh/authorized_keys", privileged: false
  end
  
  config.vm.define "inst02" do |inst02|
    inst02.vm.box = "ubuntu/trusty64"
    inst02.vm.hostname = "inst02"
    inst02.vm.network :private_network, ip: "10.10.12.64"
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    config.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
    config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
    config.vm.provision 'shell', inline: "echo \"#{ssh_pub_key}\" >> /home/vagrant/.ssh/authorized_keys", privileged: false
  end

  config.vm.define "inst03" do |inst03|
    inst03.vm.box = "ubuntu/trusty64"
    inst03.vm.hostname = "inst03"
    inst03.vm.network :private_network, ip: "10.10.12.65"
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    config.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
    config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
    config.vm.provision 'shell', inline: "echo \"#{ssh_pub_key}\" >> /home/vagrant/.ssh/authorized_keys", privileged: false
  end
end